# Generated by Django 3.1.7 on 2021-04-03 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('quantity', models.CharField(blank=True, max_length=2, null=True, verbose_name='Кол-во продукта')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип продукта')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='product.typeproduct')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='Дата покупки')),
                ('sum_product', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сумма покупки')),
                ('product_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='product.product')),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
